name: Release

on: 
    push: 
        branches:
            - main 

jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: [blue, green]

        steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build Docker Image
          run: 	docker build --build-arg VERSION=${{matrix.version}} -t ${{github.event.repository.name}}:${{matrix.version}} ./../../
        
        - name: Build and Push Docker Image
          id: docker_build
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.version }}
        