name: Release

on: 
    push: 
        branches:
            - main 

jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: [green, blue]

        steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build Docker Image
          run: 	docker build --build-arg VERSION=${{matrix.version}} -t ${{secrets.DOCKERHUB_USERNAME}}/${{github.event.repository.name}}:${{matrix.version}} .

        - name: Push Docker Image
          run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.version }}
    